export interface MaterialIcons {
  cloud_upload?: (CloudUploadEntityOrAccountBoxEntityOrAccountCircleEntityOrAnnouncementEntityOrCameraEntityOrCameraEnhanceEntityOrFavoriteEntityOrFavoriteBorderEntityOrHomeEntityOrSearchEntityOrPowerOffEntityOrPowerEntity)[] | null;
  account_box?: (CloudUploadEntityOrAccountBoxEntityOrAccountCircleEntityOrAnnouncementEntityOrCameraEntityOrCameraEnhanceEntityOrFavoriteEntityOrFavoriteBorderEntityOrHomeEntityOrSearchEntityOrPowerOffEntityOrPowerEntity)[] | null;
  account_circle?: (CloudUploadEntityOrAccountBoxEntityOrAccountCircleEntityOrAnnouncementEntityOrCameraEntityOrCameraEnhanceEntityOrFavoriteEntityOrFavoriteBorderEntityOrHomeEntityOrSearchEntityOrPowerOffEntityOrPowerEntity)[] | null;
  announcement?: (CloudUploadEntityOrAccountBoxEntityOrAccountCircleEntityOrAnnouncementEntityOrCameraEntityOrCameraEnhanceEntityOrFavoriteEntityOrFavoriteBorderEntityOrHomeEntityOrSearchEntityOrPowerOffEntityOrPowerEntity)[] | null;
  camera?: (CloudUploadEntityOrAccountBoxEntityOrAccountCircleEntityOrAnnouncementEntityOrCameraEntityOrCameraEnhanceEntityOrFavoriteEntityOrFavoriteBorderEntityOrHomeEntityOrSearchEntityOrPowerOffEntityOrPowerEntity)[] | null;
  camera_enhance?: (CloudUploadEntityOrAccountBoxEntityOrAccountCircleEntityOrAnnouncementEntityOrCameraEntityOrCameraEnhanceEntityOrFavoriteEntityOrFavoriteBorderEntityOrHomeEntityOrSearchEntityOrPowerOffEntityOrPowerEntity)[] | null;
  favorite?: (CloudUploadEntityOrAccountBoxEntityOrAccountCircleEntityOrAnnouncementEntityOrCameraEntityOrCameraEnhanceEntityOrFavoriteEntityOrFavoriteBorderEntityOrHomeEntityOrSearchEntityOrPowerOffEntityOrPowerEntity)[] | null;
  favorite_border?: (CloudUploadEntityOrAccountBoxEntityOrAccountCircleEntityOrAnnouncementEntityOrCameraEntityOrCameraEnhanceEntityOrFavoriteEntityOrFavoriteBorderEntityOrHomeEntityOrSearchEntityOrPowerOffEntityOrPowerEntity)[] | null;
  home?: (CloudUploadEntityOrAccountBoxEntityOrAccountCircleEntityOrAnnouncementEntityOrCameraEntityOrCameraEnhanceEntityOrFavoriteEntityOrFavoriteBorderEntityOrHomeEntityOrSearchEntityOrPowerOffEntityOrPowerEntity)[] | null;
  search?: (CloudUploadEntityOrAccountBoxEntityOrAccountCircleEntityOrAnnouncementEntityOrCameraEntityOrCameraEnhanceEntityOrFavoriteEntityOrFavoriteBorderEntityOrHomeEntityOrSearchEntityOrPowerOffEntityOrPowerEntity)[] | null;
  power_off?: (CloudUploadEntityOrAccountBoxEntityOrAccountCircleEntityOrAnnouncementEntityOrCameraEntityOrCameraEnhanceEntityOrFavoriteEntityOrFavoriteBorderEntityOrHomeEntityOrSearchEntityOrPowerOffEntityOrPowerEntity)[] | null;
  power?: (CloudUploadEntityOrAccountBoxEntityOrAccountCircleEntityOrAnnouncementEntityOrCameraEntityOrCameraEnhanceEntityOrFavoriteEntityOrFavoriteBorderEntityOrHomeEntityOrSearchEntityOrPowerOffEntityOrPowerEntity)[] | null;
}
export interface CloudUploadEntityOrAccountBoxEntityOrAccountCircleEntityOrAnnouncementEntityOrCameraEntityOrCameraEnhanceEntityOrFavoriteEntityOrFavoriteBorderEntityOrHomeEntityOrSearchEntityOrPowerOffEntityOrPowerEntity {
  path: string;
  fill?: string | null;
}
