export interface MaterialIcons {
  cloud_upload?: (CloudUploadEntityOrAccountBoxEntityOrAccountCircleEntityOrAnnouncementEntityOrCameraEntityOrCameraEnhanceEntityOrCancelEntityOrFavoriteEntityOrFavoriteBorderEntityOrHomeEntityOrSearchEntityOrPowerOffEntityOrPowerEntityOrKeyboardArrowDownEntityOrLockOpenEntityOrLockEntity)[] | null;
  account_box?: (CloudUploadEntityOrAccountBoxEntityOrAccountCircleEntityOrAnnouncementEntityOrCameraEntityOrCameraEnhanceEntityOrCancelEntityOrFavoriteEntityOrFavoriteBorderEntityOrHomeEntityOrSearchEntityOrPowerOffEntityOrPowerEntityOrKeyboardArrowDownEntityOrLockOpenEntityOrLockEntity)[] | null;
  account_circle?: (CloudUploadEntityOrAccountBoxEntityOrAccountCircleEntityOrAnnouncementEntityOrCameraEntityOrCameraEnhanceEntityOrCancelEntityOrFavoriteEntityOrFavoriteBorderEntityOrHomeEntityOrSearchEntityOrPowerOffEntityOrPowerEntityOrKeyboardArrowDownEntityOrLockOpenEntityOrLockEntity)[] | null;
  announcement?: (CloudUploadEntityOrAccountBoxEntityOrAccountCircleEntityOrAnnouncementEntityOrCameraEntityOrCameraEnhanceEntityOrCancelEntityOrFavoriteEntityOrFavoriteBorderEntityOrHomeEntityOrSearchEntityOrPowerOffEntityOrPowerEntityOrKeyboardArrowDownEntityOrLockOpenEntityOrLockEntity)[] | null;
  camera?: (CloudUploadEntityOrAccountBoxEntityOrAccountCircleEntityOrAnnouncementEntityOrCameraEntityOrCameraEnhanceEntityOrCancelEntityOrFavoriteEntityOrFavoriteBorderEntityOrHomeEntityOrSearchEntityOrPowerOffEntityOrPowerEntityOrKeyboardArrowDownEntityOrLockOpenEntityOrLockEntity)[] | null;
  camera_enhance?: (CloudUploadEntityOrAccountBoxEntityOrAccountCircleEntityOrAnnouncementEntityOrCameraEntityOrCameraEnhanceEntityOrCancelEntityOrFavoriteEntityOrFavoriteBorderEntityOrHomeEntityOrSearchEntityOrPowerOffEntityOrPowerEntityOrKeyboardArrowDownEntityOrLockOpenEntityOrLockEntity)[] | null;
  cancel?: (CloudUploadEntityOrAccountBoxEntityOrAccountCircleEntityOrAnnouncementEntityOrCameraEntityOrCameraEnhanceEntityOrCancelEntityOrFavoriteEntityOrFavoriteBorderEntityOrHomeEntityOrSearchEntityOrPowerOffEntityOrPowerEntityOrKeyboardArrowDownEntityOrLockOpenEntityOrLockEntity)[] | null;
  close?: (CloseEntity)[] | null;
  favorite?: (CloudUploadEntityOrAccountBoxEntityOrAccountCircleEntityOrAnnouncementEntityOrCameraEntityOrCameraEnhanceEntityOrCancelEntityOrFavoriteEntityOrFavoriteBorderEntityOrHomeEntityOrSearchEntityOrPowerOffEntityOrPowerEntityOrKeyboardArrowDownEntityOrLockOpenEntityOrLockEntity)[] | null;
  favorite_border?: (CloudUploadEntityOrAccountBoxEntityOrAccountCircleEntityOrAnnouncementEntityOrCameraEntityOrCameraEnhanceEntityOrCancelEntityOrFavoriteEntityOrFavoriteBorderEntityOrHomeEntityOrSearchEntityOrPowerOffEntityOrPowerEntityOrKeyboardArrowDownEntityOrLockOpenEntityOrLockEntity)[] | null;
  home?: (CloudUploadEntityOrAccountBoxEntityOrAccountCircleEntityOrAnnouncementEntityOrCameraEntityOrCameraEnhanceEntityOrCancelEntityOrFavoriteEntityOrFavoriteBorderEntityOrHomeEntityOrSearchEntityOrPowerOffEntityOrPowerEntityOrKeyboardArrowDownEntityOrLockOpenEntityOrLockEntity)[] | null;
  search?: (CloudUploadEntityOrAccountBoxEntityOrAccountCircleEntityOrAnnouncementEntityOrCameraEntityOrCameraEnhanceEntityOrCancelEntityOrFavoriteEntityOrFavoriteBorderEntityOrHomeEntityOrSearchEntityOrPowerOffEntityOrPowerEntityOrKeyboardArrowDownEntityOrLockOpenEntityOrLockEntity)[] | null;
  power_off?: (CloudUploadEntityOrAccountBoxEntityOrAccountCircleEntityOrAnnouncementEntityOrCameraEntityOrCameraEnhanceEntityOrCancelEntityOrFavoriteEntityOrFavoriteBorderEntityOrHomeEntityOrSearchEntityOrPowerOffEntityOrPowerEntityOrKeyboardArrowDownEntityOrLockOpenEntityOrLockEntity)[] | null;
  power?: (CloudUploadEntityOrAccountBoxEntityOrAccountCircleEntityOrAnnouncementEntityOrCameraEntityOrCameraEnhanceEntityOrCancelEntityOrFavoriteEntityOrFavoriteBorderEntityOrHomeEntityOrSearchEntityOrPowerOffEntityOrPowerEntityOrKeyboardArrowDownEntityOrLockOpenEntityOrLockEntity)[] | null;
  keyboard_arrow_down?: (CloudUploadEntityOrAccountBoxEntityOrAccountCircleEntityOrAnnouncementEntityOrCameraEntityOrCameraEnhanceEntityOrCancelEntityOrFavoriteEntityOrFavoriteBorderEntityOrHomeEntityOrSearchEntityOrPowerOffEntityOrPowerEntityOrKeyboardArrowDownEntityOrLockOpenEntityOrLockEntity)[] | null;
  lock_open?: (CloudUploadEntityOrAccountBoxEntityOrAccountCircleEntityOrAnnouncementEntityOrCameraEntityOrCameraEnhanceEntityOrCancelEntityOrFavoriteEntityOrFavoriteBorderEntityOrHomeEntityOrSearchEntityOrPowerOffEntityOrPowerEntityOrKeyboardArrowDownEntityOrLockOpenEntityOrLockEntity)[] | null;
  lock?: (CloudUploadEntityOrAccountBoxEntityOrAccountCircleEntityOrAnnouncementEntityOrCameraEntityOrCameraEnhanceEntityOrCancelEntityOrFavoriteEntityOrFavoriteBorderEntityOrHomeEntityOrSearchEntityOrPowerOffEntityOrPowerEntityOrKeyboardArrowDownEntityOrLockOpenEntityOrLockEntity)[] | null;
}
export interface CloudUploadEntityOrAccountBoxEntityOrAccountCircleEntityOrAnnouncementEntityOrCameraEntityOrCameraEnhanceEntityOrCancelEntityOrFavoriteEntityOrFavoriteBorderEntityOrHomeEntityOrSearchEntityOrPowerOffEntityOrPowerEntityOrKeyboardArrowDownEntityOrLockOpenEntityOrLockEntity {
  path: string;
  fill?: string | null;
}
export interface CloseEntity {
  path: string;
  fill: string;
}
